example_data_fetch_naver_news = {
    "lastBuildDate": "Thu, 24 Aug 2023 12:52:34 +0900",
    "total": 383245,
    "start": 1,
    "display": 10,
    "items": [
        {
            "title": "YG 떠난 방예담, GF엔터 전속계약...프로듀서·가수로 활동",
            "originallink": "https://isplus.com/article/view/isp202308240053",
            "link": "https://n.news.naver.com/mnews/article/241/0003296497?sid=106",
            "description": "특히 GF엔터테인먼트 남궁찬 대표는 김현철 등 수많은 뮤지션과 로엔엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자다. 방예담은 앞으로 GF엔터테인먼트와 손잡고 활발한 음악 활동을 펼칠... ",
            "pubDate": "Thu, 24 Aug 2023 12:14:00 +0900",
        },
        {
            "title": "[단독] 정이서, 임상춘 신작 &apos;폭싹 속았수다&apos; 합류…<b>아이유</b>·박보검과 호흡",
            "originallink": "https://star.ytn.co.kr/_sn/0117_202308241200027755",
            "link": "https://n.news.naver.com/mnews/article/052/0001926939?sid=106",
            "description": "&apos;폭싹 속았수다&apos;는 1950년대 제주에서 태어난 &apos;반항아&apos; 애순이와 &apos;무쇠&apos; 관식기의 모험 가득한 일생을 사계절로 풀어낸 드라마로, <b>아이유</b>, 박보검 씨 등과 연기 호흡을 맞춘다. &apos;폭싹 속았수다&apos;는 드라마 &apos;백희가 돌아왔다... ",
            "pubDate": "Thu, 24 Aug 2023 12:00:00 +0900",
        },
        {
            "title": "YG 떠난 방예담, 세 둥지 찾았다…GF엔터와 손잡아",
            "originallink": "https://www.munhwa.com/news/view.html?no=2023082401039912069005",
            "link": "https://n.news.naver.com/mnews/article/021/0002590065?sid=106",
            "description": "한편 방예담이 계약한 GF엔터테인먼트에는 그룹 킹덤이 소속되어 있다. GF엔터테인먼트 남궁찬 대표는 가수 김현철 등 수많은 뮤지션과 로엔엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자다.",
            "pubDate": "Thu, 24 Aug 2023 11:49:00 +0900",
        },
        {
            "title": "갑작스럽게 YG 떠났던 방예담, 1년 만에 근황 공개됐다 (사진)",
            "originallink": "https://www.wikitree.co.kr/articles/880815",
            "link": "https://www.wikitree.co.kr/articles/880815",
            "description": "GF 남궁찬 대표는 김현철 등 수많은 뮤지션과 로엔엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자다. 이에 YG를 떠나 GF에 새 둥지를 튼 방예담이 어떤 활동을 펼칠지 기대가 모이고 있다.",
            "pubDate": "Thu, 24 Aug 2023 11:20:00 +0900",
        },
        {
            "title": "올해 가요계에도 부는 걸그룹 바람..누가 잠재울까 [Oh!쎈 레터]",
            "originallink": "http://www.osen.co.kr/article/G1112166663",
            "link": "https://n.news.naver.com/mnews/article/109/0004913656?sid=106",
            "description": "이외에도 독보적 음원 강자 <b>아이유</b> 역시 올해 데뷔 15주년을 맞이한 만큼 하반기 컴백 가능성이 높은 바, <b>아이유</b>의 신곡 역시 차트에서 좋은 성적을 기록할 것으로 예상된다. 올해 하반기 가요계도 치열한 경쟁이... ",
            "pubDate": "Thu, 24 Aug 2023 11:19:00 +0900",
        },
        {
            "title": "방예담, GF 엔터테인먼트와 전속 계약 체결",
            "originallink": "https://www.bntnews.co.kr/article/view/bnt202308240029",
            "link": "https://www.bntnews.co.kr/article/view/bnt202308240029",
            "description": "특히 GF 엔터테인먼트 남궁찬 대표는 김현철 등 수많은 뮤지션과 로엔 엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자다. 한편, 방예담은 앞으로 GF 엔터테인먼트와 손잡고 활발한 음악 활동을... ",
            "pubDate": "Thu, 24 Aug 2023 11:06:00 +0900",
        },
        {
            "title": "&quot;20만 원짜리 아이돌 공연이랑 비교된다&quot; 말 나오고 있는 <b>아이유</b> &apos;팬콘서트&apos; ...",
            "originallink": "https://www.wikitree.co.kr/articles/880803",
            "link": "https://www.wikitree.co.kr/articles/880803",
            "description": "가수 겸 배우 <b>아이유</b>가 팬콘서트 소식을 전한 가운데 티켓 가격이 네티즌들 눈길을 끌었다. 앞서 지난 22일 <b>아이유</b> 소속사 이담 엔터테인먼트는 “<b>아이유</b>와 유애나가 함께 한 모든 순간 데뷔부터 지금까지 서로가... ",
            "pubDate": "Thu, 24 Aug 2023 11:00:00 +0900",
        },
        {
            "title": "&apos;잊혀진 천재&apos; 방예담의 힘찬 홀로서기 &quot;연내 컴백 목표&quot;[★FOCUS]",
            "originallink": "https://www.starnewskorea.com/stview.php?no=2023082410221419943",
            "link": "https://n.news.naver.com/mnews/article/108/0003176687?sid=106",
            "description": "방예담과 계약한 GF엔터테인먼트를 이끌고 있는 남궁찬 대표는 김현철 등 수많은 뮤지션과 로엔엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자로 잘 알려져 있다. 남궁찬 대표는 스타뉴스에 &quot;1년... ",
            "pubDate": "Thu, 24 Aug 2023 10:38:00 +0900",
        },
        {
            "title": "방예담 GF엔터서 새출발 &apos;킹덤과 한솥밥&apos;…프로듀서·솔로 활동 예고",
            "originallink": "https://sports.hankooki.com/news/articleView.html?idxno=6837644",
            "link": "https://sports.hankooki.com/news/articleView.html?idxno=6837644",
            "description": "특히 GF엔터테인먼트 남궁찬 대표는 김현철, <b>아이유</b> 등 수많은 뮤지션들의 매니지먼트를 맡았던 가요계 베테랑 제작자다. 방예담은 앞으로 GF엔터테인먼트와 손잡고 활발한 음악 활동을 펼칠 예정이다.",
            "pubDate": "Thu, 24 Aug 2023 10:34:00 +0900",
        },
        {
            "title": "방예담, GF엔터에 새 둥지…전속 계약 체결",
            "originallink": "http://www.fnnews.com/news/202308241027336048",
            "link": "https://n.news.naver.com/mnews/article/014/0005061481?sid=106",
            "description": "특히 GF엔터테인먼트 남궁찬 대표는 김현철 등 수많은 뮤지션과 로엔엔터테인먼트에서 <b>아이유</b> 매니지먼트를 맡았던 가요계 베테랑 제작자다. 한편 방예담은 앞으로 GF엔터테인먼트와 손잡고 활발한 음악 활동을 펼칠... ",
            "pubDate": "Thu, 24 Aug 2023 10:29:00 +0900",
        },
    ],
}
